phrase:
  access_token: ${{ secrets.PHRASE_TOKEN }}
  project_id: 5a7501ac1e70e4b98f959b740d92e920
  file_format: nested_json 

  push:
    sources:
    - file: ./src/assets/translations/<locale_code>.json          
  pull:
    targets:
    - file: ./src/assets/translations/<locale_code.json