phrase:
  access_token: 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
  project_id: 5a7501ac1e70e4b98f959b740d92e920
  file_format: nested_json 

  push:
    sources:
    - file: ./src/assets/translations/en.json          
  pull:
    targets:
    - file: ./src/assets/translations/en.json