phrase:
  access_token: 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
  project_id: 5a7501ac1e70e4b98f959b740d92e920
  file_format: nested_json 

  push:
    sources:
    - file: ./src/assets/translations/en.json          
  pull:
    targets:
    - file: ./src/assets/translations/en.json